### PR TITLE
ADD Figlet to Beautify CLI

### PR DESCRIPTION
**Pull request by hcktheheaven**
addfiglet

### CODE REVIEW

**Comment by hcktheheaven** [comment]
Please Review @rajikaimal @rehrumesh .

**Comment by rehrumesh** [comment]
This is great. Under `cli-commands` shall we create a `common` dir to put out all the commonly used modules and use it every other place? Also would appreciate if you could do the same with `clocal-azure`

**Comment by rehrumesh** [comment]
LGTM. 👍  🥇 
@rajikaimal @dilantha111 Review?

**Comment by hcktheheaven** [comment]
Thank you! @rehrumesh for approving, I did same changes to Clocal-azure (https://github.com/cloudlibz/clocal-azure/pull/42) Do check please! :)

**Pull request merged**
