### PR TITLE
Add command registering using readdir

### PR DESCRIPTION
**Pull request by hcktheheaven**
graphical demo

### CODE REVIEW

**Comment by hcktheheaven** [comment]
@rehrumesh Please Review.

**Comment by rehrumesh** [comment]
@hcktheheaven your approach is correct. However here you have coded some hardcoded array indexes. So whenever we add a new service we will need to update the code. If you can fix that I will be happy to merge this.

**Comment by hcktheheaven** [comment]
@rehrumesh I've Removed the Hard coded hardcoded array indexes & now it is totally Dynamic.
Please Review.
screenshot

**Comment by rehrumesh** [comment]
LGTM 👍 @dilantha111 Review, please.

**Pull request merged**
